### ISSUE TITLE
Confirmation Popup

### ISSUE THREAD

**Issue by rufus87novambit** [proteusthemes/one-click-demo-import#76] opened 2016-12-15 08:23 UTC
Hello.

Thank you for the great plugin.

There is a confirmation popup if you have more than one demo configured in some way.
Your plugin use jQueryUI Dialog ( http://api.jqueryui.com/dialog ) to show popup. There are many option in dialog ( for example ‘width’, ‘min-width’, etc ), and it will be good to have possibility to overwrite some options for dialog popup.

Please let me know what you think about this.

Thank you in advance.
Regards.

**Comment by primozcigler** [comment] 2016-12-15 09:04
Hi @rufus87novambit,

Thanks for suggestion. What is your usecase for this? We would like to know first what the issue is and what you'd like to achieve, because we'd like to keep the plugin as small and lean as possible.

Thanks.

**Comment by rufus87novambit** [comment] 2016-12-15 09:12
Hi @primozcigler.

We have a wordpress theme which use Your plugin to demo importing. In some cases we show notifications to our users on demo importing popop, and as that notifications can be long, confirmation popup has big height in some cases. So this is need to make popup larger.

I do not think that 2 lines of code will make plugin bigger. We just need a filter to overwrite some properies for jqueryui-dialog.

Thanks.

**Comment by capuderg** [comment] 2016-12-15 09:16
Hi,

we'll add the filter as discussed in the support ticket: https://wordpress.org/support/topic/confirmation-popup-3/

Take care!

**Comment by rufus87novambit** [comment] 2016-12-15 09:18
Hello.

Thank you very much.

Regards

**Comment by primozcigler** [comment] 2016-12-15 09:25
Hi there,

OK, you have a valid point now.

> I do not think that 2 lines of code will make plugin bigger.

This is how it usually begins. Fast forward couple of months, every request and wish being implemented without debate and we end up twice the size (4x the complexity) of the original plugin (or any codebase for that matter).

I firmly believe that it is easier to argue about the feature requests when there is a clear issue presented. I can see now the gist of your problem.

As @capuderg said we will most probably implement this, but no ETA for now. My suggestion would be that you fork this repo, implement the changes and submit a pull request. You will be the most qualified person to do it (and test it) as you're scratching your own itch, right?

**Comment by rufus87novambit** [comment] 2016-12-15 09:30
Hello. Thanks. Will do as soon as possible possible

**Comment by primozcigler** [comment] 2016-12-15 09:35
Great to hear!

**Comment by capuderg** [comment] 2017-01-08 09:36
Hi @rufus87novambit,

thanks for your PR. I've merged it and it will be in the next plugin release.

Take care!

**Closed by capuderg** 2017-01-08 09:36 UTC
Labels: enhancement, feature request
