### ISSUE TITLE
Widget data & demo content xml not importing.

### ISSUE THREAD

**Issue by ashawkat** [proteusthemes/one-click-demo-import#114] opened 2017-07-18 12:47 UTC
I tried to use the plugin for demo importing the content. But what I'm having issues is that the plugin is not importing any demo content from the xml file though it's showing message that it's imported. But actually nothing imported don't know why.
When adding widget file either WIE or Json it always says that file is not readable. I tried to export widgets using 2 different plugins given below:
https://wordpress.org/plugins/widget-importer-exporter/
https://wordpress.org/plugins/widget-settings-importexport/

but importer says that it can't read the files then what should I do which exporter should I use.
It only imports the theme option data that's it nothing else. If it's a bug or something else. Can you please let me know about this issue. I'm on a deadline but can't do anything with this importer. Really eager or seeking a help for this one.

**Comment by capuderg** [comment] 2017-07-19 19:14
Hi,

for widgets export, this is the correct plugin: https://wordpress.org/plugins/widget-importer-exporter/, so you used the correct plugin.

The file not being readable... I would guess, that the problem is with file permissions...

How did you try to import the content and the widgets? Via the manual uploader, or via predefined demo imports? If it was with predefined demo imports, did you setup the import files so that they are pulled from the theme folder, or are they pulled from server?

Could you please show me the log file of the demo import (the file should be in the Media section).

Take care!

**Comment by ashawkat** [comment] 2017-07-20 05:47
Hi,

I've used this plugin but the result is 0. I'm linking up the xml file & widgets wie file so that you can understand. Also I've used both tactics predefined & upload system both one fails. If I provide the widget exporter file then it shows error but without the widget file it shows that import complete but no content imports. Please help a bit here.
Log File: https://www.dropbox.com/s/1f9qc4q2vq3luto/log_file_2017-07-20__05-46-06.txt?dl=0
Content XML: https://www.dropbox.com/s/fjdns9j66etxiso/demo-content.xml?dl=0
Widgets WIE: https://www.dropbox.com/s/bhdscrc5knxv9c5/widgets.wie?dl=0
Above are the files that you may have a look. I'm really frustrated as everyone else is importing with this one why not me. I'm trying to import but it's not importing at all. Really frustrated. Please have a look and let me know what I'm doing wrong.
It always shows this error: http://prntscr.com/fxxdsn

**Comment by capuderg** [comment] 2017-07-21 12:17
Hi,

I'll probably have some time over the weekend and I'll test it out then.

**Comment by ashawkat** [comment] 2017-07-22 03:25
@capuderg please do let me know what's happening in there. I really need this work ASAP. Everything is done except this demo importer & am really worried about this one. :(

**Comment by capuderg** [comment] 2017-07-23 16:35
Hi @ashawkat,

both of the files (the content XML and the widgets WIE) were "corrupted". Both of the files had one extra empty line right at the start of the file, which is not allowed in XML, so the content did not import for you. Once I removed this empty line, the content imported ok.

In the widgets.wie, there was an empty first line and also a missing closing curly bracket at the very end of the file. Once I fixed that, the widgets imported ok as well.

You should always validate the XML and the WIE (JSON) file, before using them.

Have a nice weekend!

**Closed by capuderg** 2017-07-23 16:35 UTC

**Comment by ashawkat** [comment] 2017-07-23 17:36
Hi @capuderg ,
Sorry for the trouble but can you please forward me a link to the edited xml & wie file that you imported. I would like to check what happened in there. Please it'll be a big help.
Thanks

**Comment by ashawkat** [comment] 2017-07-23 18:04
Hi @capuderg 
Anyway thanks a lot for the help. I was really frustrated that's why I wasn't able to check that one. Thanks a lot again for such help. And yes it's really a good importer though. Everything imported perfectly except some image but it's worthy of that. 👍

**Comment by capuderg** [comment] 2017-07-23 18:33
Hi,

no problem :)

I would really appreciate it, if you can leave a 5 star review on our plugin page: https://wordpress.org/plugins/one-click-demo-import/#reviews

Thanks and have a nice day!
