### ISSUE TITLE
Can I select a menu in a Custom Menu widget after import?

### ISSUE THREAD

**Issue by transbetacism** [proteusthemes/one-click-demo-import#99] opened 2017-04-09 15:30 UTC
I am importing menus and widgets, which is working fine. But when I import a Custom Menu widget, I cannot set which menu should be shown in the widget.

Note that this is just a menu selected in a widget, so I cannot assign via `set_theme_mode`

![Custom Menu widget](https://cloud.githubusercontent.com/assets/9765146/24838520/bc0808d4-1d49-11e7-8142-c5dc948e9f15.png)

I import it like this:

    nav_menu-14":{"title":"Follow Us","nav_menu":45}}

It successfully adds a Custom Menu widget, but no menu is set. The reason is that it is trying to set a menu with an ID of 45. When importing the menu, it says that the ID should be 45, but it is not set to 45. I think WordPress picks up the first ID available.

Therefore, I don't know what id to set in the .wie file... I have tried changing 45 to "Social" instead, which is the name of the menu, but that doesn't work....

**Is there any way to solve this?**

_Let me know if I need to clarify further._

**Comment by capuderg** [comment] 2017-04-09 17:25
Hi,

thanks for describing the issue in such detail 👍 

Yeah, I know about this issue and you are totally correct. When the menus are imported in a WP site, they get different IDs from the ones on the original site (exporting site). So the old IDs in the .wie file are useless.

This is something that could be fixed, but I've never looked at the problem in detail. I will probably do that in the near future. The solution, from the top of my head, would be to collect the new IDs together with the old ones (during the content import) and reassign them to the custom menu widgets after the widget import is done.

No promises as to how fast I will fix this :)

If you would like to solve this issue, than you are more than welcome to do so :) Create a PR and I'll merge it...

Take care!

**Comment by capuderg** [comment] 2017-04-10 20:10
Hi @transbetacism,

I had a spare hour today and I think I fixed this issue.

Could you please try this v2.2.2-RC1 of the plugin. [Download it here](https://drive.google.com/file/d/0B1ApQRsFtBI3UnA5VFlRS01ZbDA/view?usp=sharing).

Let me know, if it works as it should.

Take care!

**Comment by transbetacism** [comment] 2017-04-17 14:49
Sorry for the later reply. I tested it now with the same results as before.

Actually, the menu is shown in the frontend but not set in the backend (same thing for the old version and v2.2.2-RC1). See here: http://share.hellodetail.com/k29x

**Comment by capuderg** [comment] 2017-04-17 15:37
Hm, that's strange...

I've just tested again and it's working ok on our themes... 

Did you import on a fresh WP installation?

Could you maybe send me your theme zip file, so I can debug it on your theme?

The solution I used was to get the array of old and new menu IDs and then modify the widgets import data, by replacing the old ID with the new one...

Take care!

**Comment by capuderg** [comment] 2017-05-02 14:25
Hi @transbetacism,

did you have a chance to try this out on the fresh WP import?

Take care!

**Comment by transbetacism** [comment] 2017-05-03 15:39
I just tested on a fresh install with the same results. Can you please give me an e-mail address where I can send my theme?

Thanks!

**Comment by capuderg** [comment] 2017-05-04 18:20
My email address is: same username as here @ gmail.com

**Comment by capuderg** [comment] 2017-05-07 08:24
Hi @transbetacism,

did you change the contents of your widgets import file?

This is how your custom menu widget data looks like in the import file:

`"nav_menu-9":{"title":"Customer Service","nav_menu":"Customer Service"}`

And this is how it looks like in our import file:

`"nav_menu-5":{"title":"NAVIGATION","nav_menu":11}`

The `nav_menu` data should be the ID and not the title of the menu.

Please try to export the widgets file again and try the import with the release candidate version of the plugin. That should work.

Take care!

**Closed** 2017-05-07 08:31 UTC
Labels: bug

**Comment by capuderg** [comment] 2017-05-28 09:00
Hi,

the plugin update with this added code was just released (available on https://wordpress.org/plugins/one-click-demo-import/).

If you can, please test is out and let me know, if something is not working as it should.

Take care!

**Comment by shofer4eto** [comment] 2019-01-04 15:08
Hi,

Having the same issue with Menus not getting assigned within widgets after import. Running 2.5.1 of your great plugin, has anyone succeeded with it yet? 
Thanks!

**Comment by DeoThemes** [comment] 2019-10-20 00:28
Omg, I've gone nuts with this issue. The solution was to modify widgets.wie and change id from string to integer,

`
"nav_menu-2":{"title":"Solutions","nav_menu":24}
`

**Comment by shovanuk** [comment] 2020-03-31 22:47
The issue is `"nav_menu":24`

The menu id is not always 24, it will change based on the installation. 

I would be better if we can import it by menu's nice name

- Menu Name: Category 1
- Menu Nice Name: category-1

Possible update 
`"nav_menu-2":{"title":"Solutions","nav_menu":"category-1"}`

Unfortunately, the above **does not** work for me. Any idea?

**Comment by DeoThemes** [comment] 2020-04-17 15:34
This issue is still not fixed. What I discovered during my debugging is that ID of the menu is not always the same. When I install WooCommerce on my fresh WordPress installation it creates it's own rows with ID inside of wp_terms table:

1 | uncategorized
2 | simple | simple
3 | grouped | grouped | 0
4 | variable | variable | 0
5 | external | external | 0
6 | exclude-from-search | exclude-from-search | 0
7 | exclude-from-catalog | exclude-from-catalog | 0
8 | featured | featured | 0
9 | outofstock | outofstock | 0
10 | rated-1 | rated-1 | 0
11 | rated-2 | rated-2 | 0
12 | rated-3 | rated-3 | 0
13 | rated-4 | rated-4 | 0
14 | rated-5

Therefore the menu ID assigned to the remaining empty ID's. In my case on my localhost the menu ID is 3, but when I import it on a fresh WooCommerce installation, the ID becomes 72.

How to fix?
