### ISSUE TITLE
Fatal error: Cannot redeclare class WP_Importer_Logger

### ISSUE THREAD

**Issue by manake** [proteusthemes/one-click-demo-import#49] opened 2016-09-21 13:06 UTC
Fatal error: Cannot redeclare class WP_Importer_Logger on plugin activation.

**Comment by capuderg** [comment] 2016-09-21 14:00
Hi,

do you have the WP importer v2 plugin installed?

Please deactivate it first and then activate this (OCDI) plugin, after that you can activate the WP importer v2 again and it should work.

Let me know, if this works for you...

The problem is, that we use some of the WP importer v2 classes in this plugin and we make the checks for these classes, but the OCDI plugin has to be activated before the v2 importer otherwise the errors pop up.

I'm rewriting the plugin code and this should be fixed with the new rewrite. so I'll leave this ticket opened so I know I have to test this out.

Thanks for letting me know about this issue!

Take care!

**Comment by manake** [comment] 2016-09-21 14:12
Yes, I have removed "wordpress-importer" (v0.6.3) and installed "WordPress-Importer" (which is v2). It was not possible to have both plugins installed at the same time due to the same folder name.

The OCDI plugin is activated (as the first one) and WordPress Importer is not. When I try to activate WordPress Importer then at the top of the plugins page it says "Plugin could not be activated because it triggered a fatal error." and indeed it's not possible to activate the importer plugin, it remains deactivated.

It's great that is a rewrite coming, I'll wait for it then. Please keep this plugin small and simple, it's cool the way it is now.

Do you have any idea when that rewrite could be available?

**Comment by manake** [comment] 2016-09-21 14:18
I managed to make it work.

You could use https://codex.wordpress.org/Function_Reference/is_plugin_active and if "WordPress-Importer" is not active, stop the execution of this plugin.

**Comment by capuderg** [comment] 2016-09-21 14:30
Was it the other way around? First activate the wp import v2 and then the OCDI?

This plugin will always stay like it is, with minor improvements, but the core of the plugin is already build, I just don't like the code/structure, so hence the rewrite.

I don't have an estimated date for the rewrite, but now that the summer is over, I think I'll have more time to work on it :)

Take care!

**Comment by capuderg** [comment] 2016-10-31 19:53
Hi,

I'm closing this issue for now, since it will not be a problem anymore in the new version that is coming up.

We are now using our own fork of the WP importer v2 and have changed the class names and used psr-4 autoloading...

Still no actual release date on this, but this will be solved in the next plugin version.

**Closed by capuderg** 2016-10-31 19:53 UTC
Labels: bug

**Comment by capuderg** [comment] 2016-10-31 19:54
Actually this was already solved in the plugin version 1.4.0, which I released a few days ago...

Forgot to mention that here :)
