### ISSUE TITLE
When Sub Menu haveSub  Sub Menu, Menu Import Issue

### ISSUE THREAD

**Issue by pmbaldha** [proteusthemes/one-click-demo-import#92] opened 2017-02-23 07:58 UTC
I am specially thankful for this plugin. Now, I am facing issue in menu import in specific below condition. 
->I have developed menu with 2 deep level child relationships. After that, I am export all data with in xml file.
->I try to import this xml file the sub sub child's relationships with sub child is not maintained. 

Thank You in Advance.

**Comment by capuderg** [comment] 2017-02-23 18:32
Hi,

I've just tested this out. I've created [this menu](http://www.awesomescreenshot.com/image/2212284/73dd31f6bf1576b3426a3b39f47abe67) and then exported the content and imported it with our OCDI plugin and I got the same result on the importing site...

So I did not experience any issue with the menu import.

Could you please show me a screenshots of what the menu should look like and the actual import menu that you get?

Take care!

**Comment by pmbaldha** [comment] 2017-02-24 05:45
Hi,

Origional Menu is on http://i.imgur.com/Hl1dbpN.png
Imported Menu is on http://i.imgur.com/GtVK18M.png

I have depicted issue in in Imported Menu.

Thank You Very Very Much

**Comment by capuderg** [comment] 2017-02-24 19:33
Hi,

hmm, this is strange...

So the whole menu imports OK, just the "App Landing" child pages get imported under the wrong parent?

Did you try to create a new menu with the same item structure and try to export/import again? Please try that to see, if the issue is this particular menu.

If that does not help, please send me the import content XML file, so I can try it out.

Take care!

**Comment by pmbaldha** [comment] 2017-02-25 12:34
Hi,

I have developer same structured item and try to import/export.  I have faced same issue in new developed menu also.
I am attaching here my content.txt file which is the text version of content.xml. Please change the extension of file from your side, because I am not able to attach xml file here.
I am very very thankful to you. 

Thank You
 
[content.txt](https://github.com/proteusthemes/one-click-demo-import/files/801185/content.txt)

**Comment by capuderg** [comment] 2017-02-26 18:04
Hi,

that's really strange... is this the only issue with the menus?

I'll investigate a bit more in the coming week...

Take care!

**Comment by pmbaldha** [comment] 2017-02-27 08:30
Hi,

Yes, This is issue only with menu of same structure.

Thank You.

**Comment by capuderg** [comment] 2017-03-04 11:40
Hi,

could you please also try to duplicate the App Landing pages (so App Landing, App Landing 1, App Landing 2), then delete the originals and use the newly created pages in the menu.

I think there is a unique case in your menu and I think the issues are the IDs...

Let me know how it goes.

Take care!

**Comment by capuderg** [comment] 2017-05-02 14:27
Hi,

any progress on this issue? Otherwise I'll close this ticket...

Take care!

**Closed** 2017-05-02 14:27 UTC
